<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.OpenApi" Version="2.10.0" />
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" Version="9.1.2" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TicketCanvas.Common.Application\TicketCanvas.Common.Application.csproj" />
    <ProjectReference Include="..\TicketCanvas.Common.Infrastructure\TicketCanvas.Common.Infrastructure.csproj" />
    <ProjectReference Include="..\TicketCanvas.ServiceDefaults\TicketCanvas.ServiceDefaults.csproj" />
    <ProjectReference Include="..\TicketCanvas.Show.Data\TicketCanvas.Show.Data.csproj" />
  </ItemGroup>

</Project>
